CREATE PROCEDURE [dbo].[ObtenerActivos]
AS
SELECT [IdActivo]
      ,[NumeroActivo]
      ,[Placa]
      ,[Estado]
      ,[Categoria]
      ,[UbicacionD]
      ,[DescripcionCorta]
      ,[DescripcionLarga]
      ,[Modelo]
      ,[Marca]
      ,[NumeroSerie]
      ,[ObservacionesAdicionales]
      ,[EstadoLevantamiento]
       [UsuarioLevanta]
  FROM [dbo].[Activos]